name:    PROJECTNAME
version: "0.0.0"

dependencies:

- base >=4.9.1.0 
- yesod >=1.6 
- yesod-core >=1.6 
- yesod-auth >=1.6 
- yesod-static >=1.6 
- yesod-form >=1.6 
- classy-prelude >=1.5 
- classy-prelude-conduit >=1.5 
- classy-prelude-yesod >=1.5 
- bytestring >=0.10 
- text >=0.11 
- persistent >=2.9 
- persistent-postgresql >=2.13 
- persistent-template >=2.5 
- template-haskell
- shakespeare >=2.0 
- hjsmin >=0.1 
- monad-control >=0.3 
- wai-extra >=3.0 
- yaml >=0.11 
- http-client-tls >=0.3 
- http-conduit >=2.3 
- directory >=1.1 
- warp >=3.0 
- data-default
- aeson >=1.4 
- conduit >=1.0 
- monad-logger >=0.3 
- fast-logger >=2.2 
- wai-logger >=2.2 
- file-embed
- safe
- unordered-containers
- containers
- vector
- time
- case-insensitive
- wai
- foreign-store

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  PROJECTNAME:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - PROJECTNAME
    when:
    - condition: flag(library-only)
      buildable: false

# eg to enable tests make a seperate aexecutable and throw it in nixos tests
# Test suite
# tests:
#   PROJECTNAME-test:
#     main: Spec.hs
#     source-dirs: test
#     ghc-options: -Wall
#     dependencies:
#     - PROJECTNAME
#     - hspec >=2.0.0
#     - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
